In [1]:
import tensorflow as tf
tf.__version__

/Users/stephaniexia/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


'1.12.0'

In [2]:
# Create a constant operation
# This op is added as a node to the default graph
hello = tf.constant("Hello, TensorFlow!")

# start a TF session
sess = tf.Session()

# run the op and get result
print(sess.run(hello))
##
#https://stackoverflow.com/questions/6269765/what-does-the-b-character-do-in-front-of-a-string-literal

b'Hello, TensorFlow!'


In [3]:
3 # a rank 0 tensor; this is a scalar with shape []
[1. ,2., 3.] # a rank 1 tensor; this is a vector with shape [3]
[[1., 2., 3.], [4., 5., 6.]] # a rank 2 tensor; a matrix with shape [2, 3]
[[[1., 2., 3.]], [[7., 8., 9.]]] # a rank 3 tensor with shape [2, 1, 3]

[[[1.0, 2.0, 3.0]], [[7.0, 8.0, 9.0]]]

In [10]:
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0) # also tf.float32 implicitly
node3 = tf.add(node1, node2)
sess = tf.Session()
print("node1:", node1,'\n',"node2:", node2)
print("node3: ", node3)
print("sess.run(node1, node2): ", sess.run([node1, node2]))
print("sess.run(node3): ", sess.run(node3))

a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
adder_node = a + b  # + provides a shortcut for tf.add(a, b)

print(sess.run(adder_node, feed_dict={a: 3, b: 4.5}))
print(sess.run(adder_node, feed_dict={a: [1,3], b: [2, 4]}))
add_and_triple = adder_node * 3.
print(sess.run(add_and_triple, feed_dict={a: 3, b:4.5}))

node1: Tensor("Const_13:0", shape=(), dtype=float32) 
 node2: Tensor("Const_14:0", shape=(), dtype=float32)
node3:  Tensor("Add_8:0", shape=(), dtype=float32)
sess.run(node1, node2):  [3.0, 4.0]
sess.run(node3):  7.0
7.5
[3. 7.]
22.5


In [13]:
# X and Y data
#x_train = [1, 2, 3]
#y_train = [1, 2, 3]
x = [1, 2, 3]
y = [1, 2, 3]

W = tf.Variable(tf.random_normal([1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')
# Our hypothesis XW+b
hypothesis = x_train * W + b
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - y_train))
#optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
#train = optimizer.minimize(cost)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())
# Fit the line
for step in range(2001):
   sess.run(train)
   if step % 20 == 0:
       print(step, sess.run(cost), sess.run(W), sess.run(b))


0 4.355949 [0.56940526] [-1.1960759]
20 4.355949 [0.56940526] [-1.1960759]
40 4.355949 [0.56940526] [-1.1960759]
60 4.355949 [0.56940526] [-1.1960759]
80 4.355949 [0.56940526] [-1.1960759]
100 4.355949 [0.56940526] [-1.1960759]
120 4.355949 [0.56940526] [-1.1960759]
140 4.355949 [0.56940526] [-1.1960759]
160 4.355949 [0.56940526] [-1.1960759]
180 4.355949 [0.56940526] [-1.1960759]
200 4.355949 [0.56940526] [-1.1960759]
220 4.355949 [0.56940526] [-1.1960759]
240 4.355949 [0.56940526] [-1.1960759]
260 4.355949 [0.56940526] [-1.1960759]
280 4.355949 [0.56940526] [-1.1960759]
300 4.355949 [0.56940526] [-1.1960759]
320 4.355949 [0.56940526] [-1.1960759]
340 4.355949 [0.56940526] [-1.1960759]
360 4.355949 [0.56940526] [-1.1960759]
380 4.355949 [0.56940526] [-1.1960759]
400 4.355949 [0.56940526] [-1.1960759]
420 4.355949 [0.56940526] [-1.1960759]
440 4.355949 [0.56940526] [-1.1960759]
460 4.355949 [0.56940526] [-1.1960759]
480 4.355949 [0.56940526] [-1.1960759]
500 4.355949 [0.56940526] [-1.1

In [15]:
# Now we can use X and Y in place of x_data and y_data
# # placeholders for a tensor that will be always fed using feed_dict
# See http://stackoverflow.com/questions/36693740/
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)
W = tf.Variable(tf.random_normal([1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Our hypothesis XW+b
hypothesis = X * W + b
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Fit the line
for step in range(2001):
   cost_val, W_val, b_val, _ = sess.run([cost, W, b, train],feed_dict={X: [1, 2, 3], Y: [1, 2, 3]})
   if step % 20 == 0:
       print(step, cost_val, W_val, b_val)
# Testing our model
print(sess.run(hypothesis, feed_dict={X: [5]}))
print(sess.run(hypothesis, feed_dict={X: [2.5]}))
print(sess.run(hypothesis, 
                   feed_dict={X: [1.5, 3.5]}))


0 2.7938073 [0.9611542] [-1.421718]
20 0.20484978 [1.4403884] [-1.1448897]
40 0.1648995 [1.4651502] [-1.0710866]
60 0.14957257 [1.4476185] [-1.0188456]
80 0.13584256 [1.4269943] [-0.97078234]
100 0.123374306 [1.4069663] [-0.9251419]
120 0.112050585 [1.3878442] [-0.88166195]
140 0.10176607 [1.3696173] [-0.840227]
160 0.09242558 [1.3522466] [-0.8007393]
180 0.08394242 [1.3356923] [-0.76310754]
200 0.07623787 [1.319916] [-0.7272444]
220 0.069240406 [1.304881] [-0.6930665]
240 0.06288528 [1.290553] [-0.6604949]
260 0.05711341 [1.2768981] [-0.62945414]
280 0.05187132 [1.2638848] [-0.5998721]
300 0.047110375 [1.2514831] [-0.5716803]
320 0.042786386 [1.2396642] [-0.5448134]
340 0.03885926 [1.228401] [-0.5192091]
360 0.03529259 [1.2176669] [-0.4948081]
380 0.032053314 [1.2074375] [-0.47155398]
400 0.02911135 [1.1976887] [-0.44939277]
420 0.026439384 [1.1883981] [-0.428273]
440 0.02401269 [1.179544] [-0.40814576]
460 0.021808721 [1.1711061] [-0.38896444]
480 0.019807013 [1.163065] [-0.37068465]

In [16]:
#change X and Y
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)
W = tf.Variable(tf.random_normal([1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Our hypothesis XW+b
hypothesis = X * W + b
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Fit the line
for step in range(2001):
   cost_val, W_val, b_val, _ = sess.run([cost, W, b, train],feed_dict={X: [1, 2, 3], Y: [2, 3, 4]})
   if step % 20 == 0:
       print(step, cost_val, W_val, b_val)
# Testing our model
print(sess.run(hypothesis, feed_dict={X: [5]}))
print(sess.run(hypothesis, feed_dict={X: [2.5]}))
print(sess.run(hypothesis, 
                   feed_dict={X: [1.5, 3.5]}))

0 11.065117 [-0.3685079] [0.99743813]
20 0.13301973 [0.6801707] [1.4305818]
40 0.030900678 [0.788932] [1.4515779]
60 0.027249223 [0.8077764] [1.4342813]
80 0.0247408 [0.81766003] [1.4142455]
100 0.0224699 [0.8263104] [1.3948128]
120 0.020407533 [0.8344808] [1.3762616]
140 0.018534428 [0.8422605] [1.3585789]
160 0.0168333 [0.8496736] [1.3417271]
180 0.015288271 [0.85673845] [1.3256671]
200 0.013885029 [0.86347127] [1.3103619]
220 0.012610574 [0.8698877] [1.2957759]
240 0.011453128 [0.87600255] [1.2818753]
260 0.010401908 [0.88183004] [1.2686282]
280 0.009447188 [0.8873835] [1.2560037]
300 0.008580092 [0.89267606] [1.2439725]
320 0.0077925795 [0.8977198] [1.2325069]
340 0.0070773605 [0.9025266] [1.22158]
360 0.0064277537 [0.9071076] [1.2111664]
380 0.005837807 [0.91147316] [1.2012424]
400 0.0053019896 [0.91563356] [1.1917847]
420 0.0048153456 [0.9195985] [1.1827717]
440 0.004373379 [0.92337704] [1.1741822]
460 0.0039719637 [0.92697793] [1.1659962]
480 0.0036074158 [0.9304097] [1.158195]


In [17]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]] 
y_data = [[0], [0], [0], [1], [1], [1]]
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')
# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)
# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
#tf.cast(x, dtype, name=None)此函数是类型转换函数
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
   # Initialize TensorFlow variables
   sess.run(tf.global_variables_initializer())

   for step in range(10001):
       cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
       if step % 200 == 0:
           print(step, cost_val)

   # Accuracy report
   h, c, a = sess.run([hypothesis, predicted, accuracy],
                      feed_dict={X: x_data, Y: y_data})
   print("\nHypothesis: ", h, "\nCorrect (Y): ", c, "\nAccuracy: ", a)

0 0.53425497
200 0.4319168
400 0.41678366
600 0.4026415
800 0.38931838
1000 0.37671185
1200 0.3647547
1400 0.35339823
1600 0.34260356
1800 0.3323373
2000 0.32256955
2200 0.31327263
2400 0.30442047
2600 0.29598823
2800 0.2879526
3000 0.28029132
3200 0.2729833
3400 0.2660086
3600 0.25934842
3800 0.25298485
4000 0.24690108
4200 0.2410816
4400 0.23551144
4600 0.23017669
4800 0.2250642
5000 0.2201618
5200 0.21545804
5400 0.21094203
5600 0.20660377
5800 0.20243375
6000 0.19842301
6200 0.19456331
6400 0.19084685
6600 0.18726617
6800 0.18381451
7000 0.18048541
7200 0.1772728
7400 0.17417093
7600 0.17117445
7800 0.16827835
8000 0.16547787
8200 0.16276848
8400 0.16014607
8600 0.15760659
8800 0.15514636
9000 0.15276174
9200 0.15044956
9400 0.14820658
9600 0.14602973
9800 0.14391635
10000 0.14186364

Hypothesis:  [[0.02759607]
 [0.15435266]
 [0.2894528 ]
 [0.78851515]
 [0.94398165]
 [0.9816581 ]] 
Correct (Y):  [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  1.0


In [21]:
predict=tf.cast(True, dtype=tf.float32)

sess=tf.Session()
sess.run(predict)

1.0

In [34]:
# Lab 5 Logistic Regression Classifier
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('/Users/stephaniexia/Documents/Code/tensorflow tutorial/data-03-diabetes.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 8])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([8, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(-tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        cost_val,weights,_ = sess.run([cost,W, train], feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, cost_val,weights)

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect (Y): ", c, "\nAccuracy: ", a)



(759, 8) (759, 1)
0 0.9226387 [[ 1.1504499 ]
 [ 0.22871277]
 [ 2.2622318 ]
 [-0.5734556 ]
 [ 0.57770956]
 [ 2.6249194 ]
 [-0.5600849 ]
 [ 0.14174804]]
200 0.8728538 [[ 0.9887621 ]
 [ 0.04453988]
 [ 2.1779435 ]
 [-0.6438753 ]
 [ 0.48335603]
 [ 2.5170007 ]
 [-0.5819274 ]
 [ 0.06869129]]
400 0.8315248 [[ 0.8521471 ]
 [-0.13608786]
 [ 2.0928473 ]
 [-0.69878185]
 [ 0.40896076]
 [ 2.4138315 ]
 [-0.58272725]
 [ 0.02081293]]
600 0.7951244 [[ 0.72970945]
 [-0.30942744]
 [ 2.0097995 ]
 [-0.74521714]
 [ 0.34611806]
 [ 2.3140469 ]
 [-0.5766077 ]
 [-0.01457623]]
800 0.7627946 [[ 0.61681986]
 [-0.4739524 ]
 [ 1.9300094 ]
 [-0.7862866 ]
 [ 0.29106122]
 [ 2.2171159 ]
 [-0.5694703 ]
 [-0.0429705 ]]
1000 0.73412424 [[ 0.51152074]
 [-0.62916774]
 [ 1.8539692 ]
 [-0.82339764]
 [ 0.24201404]
 [ 2.1228728 ]
 [-0.5636594 ]
 [-0.06678379]]
1200 0.70876354 [[ 0.41295084]
 [-0.77508974]
 [ 1.7818307 ]
 [-0.8572369 ]
 [ 0.19803941]
 [ 2.0312874 ]
 [-0.5599788 ]
 [-0.08712628]]
1400 0.6863728 [[ 0.32067198]
 [-0.

In [35]:
# Lab 6 Softmax Classifier
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

    print('--------------')

    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')

    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')

    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')

    all = sess.run(hypothesis, feed_dict={
                   X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 3.9433942
200 0.4973698
400 0.39985913
600 0.32042462
800 0.2544058
1000 0.22787869
1200 0.20667581
1400 0.18904504
1600 0.1741306
1800 0.16134527
2000 0.15026465
--------------
[[2.3747499e-03 9.9761933e-01 5.9930662e-06]] [1]
--------------
[[0.9067683  0.08872146 0.00451032]] [0]
--------------
[[7.5586923e-09 2.7310775e-04 9.9972683e-01]] [2]
--------------
[[2.3747478e-03 9.9761933e-01 5.9930721e-06]
 [9.0676832e-01 8.8721462e-02 4.5103119e-03]
 [7.5586923e-09 2.7310775e-04 9.9972683e-01]] [1 0 2]


In [46]:
import tensorflow as tf
import random
import matplotlib.pyplot as plt
tf.set_random_seed(777)  # for reproducibility

from tensorflow.examples.tutorials.mnist import input_data
# Check out https://www.tensorflow.org/get_started/mnist/beginners for
# more information about the mnist dataset
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
batch_xs, batch_ys = mnist.train.next_batch(100)#arrays

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 

In [49]:

# Lab 7 Learning rate and Evaluation
import tensorflow as tf
import random
import matplotlib.pyplot as plt
tf.set_random_seed(777)  # for reproducibility

from tensorflow.examples.tutorials.mnist import input_data
# Check out https://www.tensorflow.org/get_started/mnist/beginners for
# more information about the mnist dataset
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

nb_classes = 10

# MNIST data image of shape 28 * 28 = 784
X = tf.placeholder(tf.float32, [None, 784])
# 0 - 9 digits recognition = 10 classes
Y = tf.placeholder(tf.float32, [None, nb_classes])

W = tf.Variable(tf.random_normal([784, nb_classes]))
b = tf.Variable(tf.random_normal([nb_classes]))

# Hypothesis (using softmax)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Test model
is_correct = tf.equal(tf.arg_max(hypothesis, 1), tf.arg_max(Y, 1))
# Calculate accuracy
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# parameters
training_epochs = 15
batch_size = 100

with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    # Training cycle
    for epoch in range(training_epochs):
        avg_cost = 0
        total_batch = int(mnist.train.num_examples / batch_size)

        for i in range(total_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            c, _ = sess.run([cost, optimizer], feed_dict={
                            X: batch_xs, Y: batch_ys})
            avg_cost += c / total_batch

        print('Epoch:', '%04d' % (epoch + 1),
              'cost =', '{:.9f}'.format(avg_cost))

    print("Learning finished")

    # Test the model using test sets
    print("Accuracy: ", accuracy.eval(session=sess, feed_dict={
          X: mnist.test.images, Y: mnist.test.labels}))

    # Get one and predict
    r = random.randint(0, mnist.test.num_examples - 1)
    print("Label: ", sess.run(tf.argmax(mnist.test.labels[r:r + 1], 1)))
    print("Prediction: ", sess.run(
        tf.argmax(hypothesis, 1), feed_dict={X: mnist.test.images[r:r + 1]}))

    plt.imshow(
        mnist.test.images[r:r + 1].reshape(28, 28),
        cmap='Greys',
        interpolation='nearest')
    plt.show()

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Epoch: 0001 cost = 2.956114819
Epoch: 0002 cost = 1.149938548
Epoch: 0003 cost = 0.896135980
Epoch: 0004 cost = 0.774797348
Epoch: 0005 cost = 0.699681105
Epoch: 0006 cost = 0.646229761
Epoch: 0007 cost = 0.606484101
Epoch: 0008 cost = 0.575170977
Epoch: 0009 cost = 0.549424710
Epoch: 0010 cost = 0.528247285
Epoch: 0011 cost = 0.510796516
Epoch: 0012 cost = 0.494784127
Epoch: 0013 cost = 0.481255902
Epoch: 0014 cost = 0.469455684
Epoch: 0015 cost = 0.458053159
Learning finished
Accuracy:  0.8869
Label:  [9]


TypeError: run() got multiple values for argument 'feed_dict'

In [50]:
# Lab 10 MNIST and NN
import tensorflow as tf
import random
# import matplotlib.pyplot as plt

from tensorflow.examples.tutorials.mnist import input_data

tf.set_random_seed(777)  # reproducibility

mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
# Check out https://www.tensorflow.org/get_started/mnist/beginners for
# more information about the mnist dataset

# parameters
learning_rate = 0.001
training_epochs = 15
batch_size = 100

# input place holders
X = tf.placeholder(tf.float32, [None, 784])
Y = tf.placeholder(tf.float32, [None, 10])

# weights & bias for nn layers
W1 = tf.Variable(tf.random_normal([784, 256]))
b1 = tf.Variable(tf.random_normal([256]))
L1 = tf.nn.relu(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([256, 256]))
b2 = tf.Variable(tf.random_normal([256]))
L2 = tf.nn.relu(tf.matmul(L1, W2) + b2)

W3 = tf.Variable(tf.random_normal([256, 10]))
b3 = tf.Variable(tf.random_normal([10]))
hypothesis = tf.matmul(L2, W3) + b3

# define cost/loss & optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(
    logits=hypothesis, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

# initialize
sess = tf.Session()
sess.run(tf.global_variables_initializer())

# train my model
for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = int(mnist.train.num_examples / batch_size)

    for i in range(total_batch):
        batch_xs, batch_ys = mnist.train.next_batch(batch_size)
        feed_dict = {X: batch_xs, Y: batch_ys}
        c, _ = sess.run([cost, optimizer], feed_dict=feed_dict)
        avg_cost += c / total_batch

    print('Epoch:', '%04d' % (epoch + 1), 'cost =', '{:.9f}'.format(avg_cost))

print('Learning Finished!')

# Test model and check accuracy
correct_prediction = tf.equal(tf.argmax(hypothesis, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print('Accuracy:', sess.run(accuracy, feed_dict={
      X: mnist.test.images, Y: mnist.test.labels}))

# Get one and predict
r = random.randint(0, mnist.test.num_examples - 1)
print("Label: ", sess.run(tf.argmax(mnist.test.labels[r:r + 1], 1)))
print("Prediction: ", sess.run(
    tf.argmax(hypothesis, 1), feed_dict={X: mnist.test.images[r:r + 1]}))

# plt.imshow(mnist.test.images[r:r + 1].
#           reshape(28, 28), cmap='Greys', interpolation='nearest')
# plt.show()


Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

Epoch: 0001 cost = 131.294641930
Epoch: 0002 cost = 37.392091682
Epoch: 0003 cost = 23.555403930
Epoch: 0004 cost = 16.285784615
Epoch: 0005 cost = 11.712277943
Epoch: 0006 cost = 8.726046864
Epoch: 0007 cost = 6.495006505
Epoch: 0008 cost = 4.737544796
Epoch: 0009 cost = 3.568460204
Epoch: 0010 cost = 2.664356393
Epoch: 0011 cost = 1.933957644
Epoch: 0012 cost = 1.549131294
Epoch: 0013 cost = 1.156215109
Epoch: 0014 cost = 0.878527616
Epoch: 0015 cost = 0.751991418
Learning Finished!
Accuracy: 0.9486
Label:  [6]
Prediction:  [5]


In [70]:
with sess.as_default():
    print(tf.reduce_sum(([[1,2],[3,4]]),axis=-1).eval())
    print(tf.reduce_mean([[1,2],[3,4]]).eval())
    print(tf.reduce_mean(tf.reduce_sum(([[1,2],[3,4]]),axis=1)).eval())

[3 7]
2
5


In [74]:

# https://www.tensorflow.org/api_guides/python/array_ops
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
tf.matmul(matrix1, matrix2).eval()

/Users/stephaniexia/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


array([[12.]], dtype=float32)

In [72]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0])

In [76]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [89]:
tr=tf.reshape(t, shape=[-1, 3]).eval()
print(tr)
tt=tf.reshape(tr,shape=[1,-1]).eval()
tf.squeeze(tt).eval()

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [79]:
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2], dtype=int32)

In [84]:
ts=tf.squeeze(t).eval()
print(ts)


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [90]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [91]:

for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


In [92]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [97]:
t1 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])
